# NOTE: Generated By HttpRunner v3.1.4
# FROM: stocknewslist_600519_sh.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseStocknewslist600519Sh(HttpRunner):

    config = Config("行情快照835033.bj")

    teststeps = [
        Step(
            RunRequest("/v2/stocknewslist")
            .get("http://114.80.155.57:22013/v2/stocknewslist")
            .with_headers(
                **{
                    "Param": "-1,,100000",
                    "Src": "d",
                    "Symbol": "600519.sh",
                    "Token": "MitakeWeb",
                    "User-Agent": "python-requests/2.25.1",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."content-type"', "text/plain; charset=UTF-8")
        ),
    ]


if __name__ == "__main__":
    TestCaseStocknewslist600519Sh().test_start()
